In [319]:
import numpy as np
from scipy.sparse.linalg import eigsh 

In [320]:
mat = np.array([[0,0, 0.1,0.1, 0.1,0],
                [0,0, 0.1,0.1, 0,0.1],
                [0.1,0.1, 0,0, 0.1,0.1],
                [0.1,0.1, 0,0, 0.1,0.1],
                [0.1,0, 0.1,0.1, 0,0],
                [0,0.1, 0.1,0.1, 0,0],], dtype='f')

In [321]:
mat

array([[0. , 0. , 0.1, 0.1, 0.1, 0. ],
       [0. , 0. , 0.1, 0.1, 0. , 0.1],
       [0.1, 0.1, 0. , 0. , 0.1, 0.1],
       [0.1, 0.1, 0. , 0. , 0.1, 0.1],
       [0.1, 0. , 0.1, 0.1, 0. , 0. ],
       [0. , 0.1, 0.1, 0.1, 0. , 0. ]], dtype=float32)

In [322]:
D = np.diag(np.sum(mat, axis= 0))

In [323]:
D

array([[0.3, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.3, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.4, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.4, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.3, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.3]], dtype=float32)

In [324]:
L = np.matrix(D - mat)

In [325]:
L

matrix([[ 0.3,  0. , -0.1, -0.1, -0.1,  0. ],
        [ 0. ,  0.3, -0.1, -0.1,  0. , -0.1],
        [-0.1, -0.1,  0.4,  0. , -0.1, -0.1],
        [-0.1, -0.1,  0. ,  0.4, -0.1, -0.1],
        [-0.1,  0. , -0.1, -0.1,  0.3,  0. ],
        [ 0. , -0.1, -0.1, -0.1,  0. ,  0.3]], dtype=float32)

In [326]:
vals, vecs = eigsh(L, k=2, which='SM')

In [327]:
vecs

array([[ 4.0824836e-01,  4.9999994e-01],
       [ 4.0824836e-01, -5.0000024e-01],
       [ 4.0824825e-01,  7.4505806e-08],
       [ 4.0824831e-01,  5.9604645e-08],
       [ 4.0824836e-01,  4.9999997e-01],
       [ 4.0824836e-01, -5.0000000e-01]], dtype=float32)

In [328]:
vals

array([6.7055225e-08, 2.0000000e-01], dtype=float32)